parameters:
    dms_meetup_api.client_factory.class: DMS\Bundle\MeetupApiBundle\Service\ClientFactory
    dms_meetup_api.key_client.class: DMS\Service\Meetup\MeetupKeyAuthClient
    dms_meetup_api.oauth_client.class: DMS\Service\Meetup\MeetupOAuthClient

services:
  dms_meetup_api.client_factory:
    class: "%dms_meetup_api.client_factory.class%"
    arguments:
      - "@session"
      - "%dms_meetup_api.client.config%"

  dms_meetup_api.key_client:
    class:    "%dms_meetup_api.key_client.class%"
    factory:  ["@dms_meetup_api.client_factory", getKeyAuthClient]

  dms_meetup_api.oauth_client:
    class:    "%dms_meetup_api.oauth_client.class%"
    factory:  ["@dms_meetup_api.client_factory", getOauthClient]

